db.restaurants.find()
db.restaurants.find({},{"restaurant_id":1,"name":1,"borough":1,"cuisine":1})
db.restaurants.find({},{_id:0,"restaurant_id":1,"name":1,"borough":1,"cuisine":1})
db.restaurants.find({},{_id:0,"restaurant_id":1,"name":1,"borough":1,"address.zipcode":1})
db.restaurants.find({"borough" : "Bronx"})
db.restaurants.find({"borough" : "Bronx"}).limit(5)
db.restaurants.find({"borough" : "Bronx"}).limit(5).skip(5)
db.restaurants.find({"grades.score":{$gt:90}},{restaurant_id:1})
db.restaurants.find({"grades.score":{$gt:80,$lt:100}},{restaurant_id:1})
db.restaurants.find({"address.coord":{$lt:-95.754168}},{restaurant_id:1})
db.restaurants.find({"cuisine":{$ne:"american"},"grades.score":{$gt:70},"address.coord":{$lt:65.754168}},{restaurant_id:1})
db.restaurants.find({"cuisine":{$ne:"american"},"grades.score":{$gt:70},"address.coord":{$lt:65.754168}},{restaurant_id:1})
db.restaurants.find({"cuisine":{$ne:"american"},"grades.grade":{$eq:"A"},"borough":{$ne:"Brooklyn"}},{restaurant_id:1})
db.restaurants.find({"name":/Wil./},{"restaurant_id":1,"name":1,"borough":1,"cuisine":1})
db.restaurants.find({"name":/.ces/},{"restaurant_id":1,"name":1,"borough":1,"cuisine":1})
db.restaurants.find({"name":/.Reg./},{"restaurant_id":1,"name":1,"borough":1,"cuisine":1})
db.restaurants.find({"borough" : "Bronx", "cuisine" : {$in:["American ","Chinese"]}},{"restaurant_id":1,"name":1,"borough":1,"cuisine":1})
db.restaurants.find({"borough" : {$in:["Staten Island","Queens","Bronx","Brooklyn"]}},{"restaurant_id":1,"name":1,"borough":1,"cuisine":1})
db.restaurants.find({"borough" : {$nin:["Staten Island","Queens","Bronx","Brooklyn"]}},{"restaurant_id":1,"name":1,"borough":1,"cuisine":1})
db.restaurants.find({"grades.score":{$lt:10}},{"restaurant_id":1,"name":1,"borough":1,"cuisine":1})
